"""initial schema

Revision ID: 30db5d429d7c
Revises: 
Create Date: 2026-05-21 13:36:57.444508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30db5d429d7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_pool',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('posted', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_jobs_pool_scraped_at', 'jobs_pool', ['scraped_at'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sent_jobs',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'job_id')
    )
    op.create_index('ix_sent_jobs_sent_at', 'sent_jobs', ['sent_at'], unique=False)
    op.create_table('users',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('exclude_keywords', sa.Text(), nullable=False),
    sa.Column('locations', sa.Text(), nullable=False),
    sa.Column('experience_years', sa.SmallInteger(), nullable=False),
    sa.Column('require_zero_experience', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('next_send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("frequency in ('daily','twice_daily','weekly')", name='ck_users_frequency'),
    sa.CheckConstraint("status in ('active','paused','unsubscribed')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index('ix_users_status_next_send_at', 'users', ['status', 'next_send_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_status_next_send_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sent_jobs_sent_at', table_name='sent_jobs')
    op.drop_table('sent_jobs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_jobs_pool_scraped_at', table_name='jobs_pool')
    op.drop_table('jobs_pool')
    # ### end Alembic commands ###
